version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: queue-nestjs
      # POSTGRES_USER: root
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis:6
    ports:
      - 6379:6379

volumes:
  postgres-data: