version: '3'

services:
  app:
    build: .
    ports:
      - 3000:300
    volumes:
      - .:/home/node/app
  
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-api
    # MYSQL_USER: user
    # MYSQL_PASSWORD: root