GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 10.51,
  "categoryId": 1
}
###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Product 1 updated",
  "price": 100.20001
}
###
DELETE http://localhost:3000/products/1